package com.neverhide.empire.quran

/**
 * Surah catalog — generated from the official AlQuran Cloud metadata API.
 * 114 surahs: number, Arabic name, English name, ayah count.
 */
data class SurahInfo(
    val number: Int,
    val arabicName: String,
    val englishName: String,
    val ayahs: Int
)

object Surahs {
    val all: List<SurahInfo> = listOf(
        SurahInfo(1, "سُورَةُ ٱلْفَاتِحَةِ", "Al-Faatiha", 7),
        SurahInfo(2, "سُورَةُ البَقَرَةِ", "Al-Baqara", 286),
        SurahInfo(3, "سُورَةُ آلِ عِمۡرَانَ", "Aal-i-Imraan", 200),
        SurahInfo(4, "سُورَةُ النِّسَاءِ", "An-Nisaa", 176),
        SurahInfo(5, "سُورَةُ المَائـِدَةِ", "Al-Maaida", 120),
        SurahInfo(6, "سُورَةُ الأَنۡعَامِ", "Al-An'aam", 165),
        SurahInfo(7, "سُورَةُ الأَعۡرَافِ", "Al-A'raaf", 206),
        SurahInfo(8, "سُورَةُ الأَنفَالِ", "Al-Anfaal", 75),
        SurahInfo(9, "سُورَةُ التَّوۡبَةِ", "At-Tawba", 129),
        SurahInfo(10, "سُورَةُ يُونُسَ", "Yunus", 109),
        SurahInfo(11, "سُورَةُ هُودٍ", "Hud", 123),
        SurahInfo(12, "سُورَةُ يُوسُفَ", "Yusuf", 111),
        SurahInfo(13, "سُورَةُ الرَّعۡدِ", "Ar-Ra'd", 43),
        SurahInfo(14, "سُورَةُ إِبۡرَاهِيمَ", "Ibrahim", 52),
        SurahInfo(15, "سُورَةُ الحِجۡرِ", "Al-Hijr", 99),
        SurahInfo(16, "سُورَةُ النَّحۡلِ", "An-Nahl", 128),
        SurahInfo(17, "سُورَةُ الإِسۡرَاءِ", "Al-Israa", 111),
        SurahInfo(18, "سُورَةُ الكَهۡفِ", "Al-Kahf", 110),
        SurahInfo(19, "سُورَةُ مَرۡيَمَ", "Maryam", 98),
        SurahInfo(20, "سُورَةُ طه", "Taa-Haa", 135),
        SurahInfo(21, "سُورَةُ الأَنبِيَاءِ", "Al-Anbiyaa", 112),
        SurahInfo(22, "سُورَةُ الحَجِّ", "Al-Hajj", 78),
        SurahInfo(23, "سُورَةُ المُؤۡمِنُونَ", "Al-Muminoon", 118),
        SurahInfo(24, "سُورَةُ النُّورِ", "An-Noor", 64),
        SurahInfo(25, "سُورَةُ الفُرۡقَانِ", "Al-Furqaan", 77),
        SurahInfo(26, "سُورَةُ الشُّعَرَاءِ", "Ash-Shu'araa", 227),
        SurahInfo(27, "سُورَةُ النَّمۡلِ", "An-Naml", 93),
        SurahInfo(28, "سُورَةُ القَصَصِ", "Al-Qasas", 88),
        SurahInfo(29, "سُورَةُ العَنكَبُوتِ", "Al-Ankaboot", 69),
        SurahInfo(30, "سُورَةُ الرُّومِ", "Ar-Room", 60),
        SurahInfo(31, "سُورَةُ لُقۡمَانَ", "Luqman", 34),
        SurahInfo(32, "سُورَةُ السَّجۡدَةِ", "As-Sajda", 30),
        SurahInfo(33, "سُورَةُ الأَحۡزَابِ", "Al-Ahzaab", 73),
        SurahInfo(34, "سُورَةُ سَبَإٍ", "Saba", 54),
        SurahInfo(35, "سُورَةُ فَاطِرٍ", "Faatir", 45),
        SurahInfo(36, "سُورَةُ يسٓ", "Yaseen", 83),
        SurahInfo(37, "سُورَةُ الصَّافَّاتِ", "As-Saaffaat", 182),
        SurahInfo(38, "سُورَةُ صٓ", "Saad", 88),
        SurahInfo(39, "سُورَةُ الزُّمَرِ", "Az-Zumar", 75),
        SurahInfo(40, "سُورَةُ غَافِرٍ", "Ghafir", 85),
        SurahInfo(41, "سُورَةُ فُصِّلَتۡ", "Fussilat", 54),
        SurahInfo(42, "سُورَةُ الشُّورَىٰ", "Ash-Shura", 53),
        SurahInfo(43, "سُورَةُ الزُّخۡرُفِ", "Az-Zukhruf", 89),
        SurahInfo(44, "سُورَةُ الدُّخَانِ", "Ad-Dukhaan", 59),
        SurahInfo(45, "سُورَةُ الجَاثِيَةِ", "Al-Jaathiya", 37),
        SurahInfo(46, "سُورَةُ الأَحۡقَافِ", "Al-Ahqaf", 35),
        SurahInfo(47, "سُورَةُ مُحَمَّدٍ", "Muhammad", 38),
        SurahInfo(48, "سُورَةُ الفَتۡحِ", "Al-Fath", 29),
        SurahInfo(49, "سُورَةُ الحُجُرَاتِ", "Al-Hujuraat", 18),
        SurahInfo(50, "سُورَةُ قٓ", "Qaaf", 45),
        SurahInfo(51, "سُورَةُ الذَّارِيَاتِ", "Adh-Dhaariyat", 60),
        SurahInfo(52, "سُورَةُ الطُّورِ", "At-Tur", 49),
        SurahInfo(53, "سُورَةُ النَّجۡمِ", "An-Najm", 62),
        SurahInfo(54, "سُورَةُ القَمَرِ", "Al-Qamar", 55),
        SurahInfo(55, "سُورَةُ الرَّحۡمَٰن", "Ar-Rahmaan", 78),
        SurahInfo(56, "سُورَةُ الوَاقِعَةِ", "Al-Waaqia", 96),
        SurahInfo(57, "سُورَةُ الحَدِيدِ", "Al-Hadid", 29),
        SurahInfo(58, "سُورَةُ المُجَادلَةِ", "Al-Mujaadila", 22),
        SurahInfo(59, "سُورَةُ الحَشۡرِ", "Al-Hashr", 24),
        SurahInfo(60, "سُورَةُ المُمۡتَحنَةِ", "Al-Mumtahana", 13),
        SurahInfo(61, "سُورَةُ الصَّفِّ", "As-Saff", 14),
        SurahInfo(62, "سُورَةُ الجُمُعَةِ", "Al-Jumu'a", 11),
        SurahInfo(63, "سُورَةُ المُنَافِقُونَ", "Al-Munaafiqoon", 11),
        SurahInfo(64, "سُورَةُ التَّغَابُنِ", "At-Taghaabun", 18),
        SurahInfo(65, "سُورَةُ الطَّلَاقِ", "At-Talaaq", 12),
        SurahInfo(66, "سُورَةُ التَّحۡرِيمِ", "At-Tahrim", 12),
        SurahInfo(67, "سُورَةُ المُلۡكِ", "Al-Mulk", 30),
        SurahInfo(68, "سُورَةُ القَلَمِ", "Al-Qalam", 52),
        SurahInfo(69, "سُورَةُ الحَاقَّةِ", "Al-Haaqqa", 52),
        SurahInfo(70, "سُورَةُ المَعَارِجِ", "Al-Ma'aarij", 44),
        SurahInfo(71, "سُورَةُ نُوحٍ", "Nooh", 28),
        SurahInfo(72, "سُورَةُ الجِنِّ", "Al-Jinn", 28),
        SurahInfo(73, "سُورَةُ المُزَّمِّلِ", "Al-Muzzammil", 20),
        SurahInfo(74, "سُورَةُ المُدَّثِّرِ", "Al-Muddaththir", 56),
        SurahInfo(75, "سُورَةُ القِيَامَةِ", "Al-Qiyaama", 40),
        SurahInfo(76, "سُورَةُ الإِنسَانِ", "Al-Insaan", 31),
        SurahInfo(77, "سُورَةُ المُرۡسَلَاتِ", "Al-Mursalaat", 50),
        SurahInfo(78, "سُورَةُ النَّبَإِ", "An-Naba", 40),
        SurahInfo(79, "سُورَةُ النَّازِعَاتِ", "An-Naazi'aat", 46),
        SurahInfo(80, "سُورَةُ عَبَسَ", "Abasa", 42),
        SurahInfo(81, "سُورَةُ التَّكۡوِيرِ", "At-Takwir", 29),
        SurahInfo(82, "سُورَةُ الانفِطَارِ", "Al-Infitaar", 19),
        SurahInfo(83, "سُورَةُ المُطَفِّفِينَ", "Al-Mutaffifin", 36),
        SurahInfo(84, "سُورَةُ الانشِقَاقِ", "Al-Inshiqaaq", 25),
        SurahInfo(85, "سُورَةُ البُرُوجِ", "Al-Burooj", 22),
        SurahInfo(86, "سُورَةُ الطَّارِقِ", "At-Taariq", 17),
        SurahInfo(87, "سُورَةُ الأَعۡلَىٰ", "Al-A'laa", 19),
        SurahInfo(88, "سُورَةُ الغَاشِيَةِ", "Al-Ghaashiya", 26),
        SurahInfo(89, "سُورَةُ الفَجۡرِ", "Al-Fajr", 30),
        SurahInfo(90, "سُورَةُ البَلَدِ", "Al-Balad", 20),
        SurahInfo(91, "سُورَةُ الشَّمۡسِ", "Ash-Shams", 15),
        SurahInfo(92, "سُورَةُ اللَّيۡلِ", "Al-Lail", 21),
        SurahInfo(93, "سُورَةُ الضُّحَىٰ", "Ad-Dhuhaa", 11),
        SurahInfo(94, "سُورَةُ الشَّرۡحِ", "Ash-Sharh", 8),
        SurahInfo(95, "سُورَةُ التِّينِ", "At-Tin", 8),
        SurahInfo(96, "سُورَةُ العَلَقِ", "Al-Alaq", 19),
        SurahInfo(97, "سُورَةُ القَدۡرِ", "Al-Qadr", 5),
        SurahInfo(98, "سُورَةُ البَيِّنَةِ", "Al-Bayyina", 8),
        SurahInfo(99, "سُورَةُ الزَّلۡزَلَةِ", "Az-Zalzala", 8),
        SurahInfo(100, "سُورَةُ العَادِيَاتِ", "Al-Aadiyaat", 11),
        SurahInfo(101, "سُورَةُ القَارِعَةِ", "Al-Qaari'a", 11),
        SurahInfo(102, "سُورَةُ التَّكَاثُرِ", "At-Takaathur", 8),
        SurahInfo(103, "سُورَةُ العَصۡرِ", "Al-Asr", 3),
        SurahInfo(104, "سُورَةُ الهُمَزَةِ", "Al-Humaza", 9),
        SurahInfo(105, "سُورَةُ الفِيلِ", "Al-Fil", 5),
        SurahInfo(106, "سُورَةُ قُرَيۡشٍ", "Quraish", 4),
        SurahInfo(107, "سُورَةُ المَاعُونِ", "Al-Maa'un", 7),
        SurahInfo(108, "سُورَةُ الكَوۡثَرِ", "Al-Kawthar", 3),
        SurahInfo(109, "سُورَةُ الكَافِرُونَ", "Al-Kaafiroon", 6),
        SurahInfo(110, "سُورَةُ النَّصۡرِ", "An-Nasr", 3),
        SurahInfo(111, "سُورَةُ المَسَدِ", "Al-Masad", 5),
        SurahInfo(112, "سُورَةُ الإِخۡلَاصِ", "Al-Ikhlaas", 4),
        SurahInfo(113, "سُورَةُ الفَلَقِ", "Al-Falaq", 5),
        SurahInfo(114, "سُورَةُ النَّاسِ", "An-Naas", 6),
    )

    fun byNumber(n: Int): SurahInfo = all[n - 1]
}
